=encoding utf8

=head1 “So, who the hell is Qoheleth?”

=head2 About

This repository contains the sources for I<“So, who the hell is Qoheleth?”>,
an illustrated, historical, fanfic screenplay by
Shlomi Fish (L<http://www.shlomifish.org/>) about what happened to the
author of the scroll of L<http://en.wikipedia.org/wiki/Ecclesiastes>
shortly after having written it.

=head2 Links

=over 4

=item * Homepage

L<http://www.shlomifish.org/humour/So-Who-The-Hell-Is-Qoheleth/>

=back

=head2 Building the Screenplay

Go to C<./so-who-the-hell-is-qoheleth/screenplay/> and type C<make> .

=head2 Ideas document / plot summary

The file C<./so-who-the-hell-is-qoheleth/ideas/ideas.pod> contains some ideas and
planning to put into the story. One can render it into XHTML by typing
C<make> .

=cut

